apiVersion: apps/v1
kind: Deployment
metadata:
  name: "devops-a3"
spec:
  selector:
    matchLabels:
      app: "devops-a3"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "devops-a3"
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "devops-a3"
        env:
          - name: DB_HOSTNAME
            value: {{ .Values.dbhost }}
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: password
          - name: DB_NAME
            value: servian
        ports:
        - containerPort: 80
